version: "3"

services:
  app:
    container_name: mongodb-nodejs-simple-webapp
    restart: always
    build: .
    ports:
      - "80:5000" # client port - service port
    links:
      - mongo

  mongo:
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - "27017:27017" # client port - service port
